name: Github Actions Pipeline

on:
    push:
      branches:
        - "*"
    pull_request:
      branches:
        - "*"    
    
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configura o .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.0.x
          dotnet-quality: 'preview'

      # Restaura as dependências do projeto
      - name: Restore dependencies
        run: dotnet restore
      
      # Compila o projeto
      - name: Build solution
        run: dotnet build --configuration Release
      
      # Executa os testes com cobertura de código usando Coverlet
      - name: Testing Running with Coverage
        run: |
         dotnet test --configuration Release --collect: "XPlat Code Coverage"

      # Gera e publica relatorio de cobertura
      - name: Upload code coverage result
        uses: codecov/codecov-action@v4
        with: 
          files: ./TestResults/**/coverage.cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}